log/urls.py
#!python
# log/urls.py
from django.conf.urls import url
from . import views
from log import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^home$', views.home, name='home'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^$',views.homepage, name='homepage'),
    url(r'^review$', views.review_list, name='review_list'),
    url(r'^apphome$', views.apphome, name='apphome'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^user/(?P<user_name>[a-z]+)/$', views.user_detail, name='user_detail'),
    url(r'^course$', views.course_list, name='course_list'),
    url(r'^faculty$', views.faculty_list, name='faculty_list'),
    url(r'^course/(?P<course_id>[0-9]+)/$', views.course_detail, name='course_detail'),
    url(r'^course/(?P<course_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^user_login$', views.user_login, name='auth'),
]

project/urls.py
#!python
# project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# Add this import
from django.conf.urls.static import static
from django.contrib.auth import views
from log.forms import LoginForm
from log.views import user_login

urlpatterns = [
    url(r'^reviews/', include('log.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^login_failed/$', views.login, {'template_name': 'login_failed.html', 'authentication_form': LoginForm}, name='login_failed'),
    url(r'^login1/$', user_login, name='auth'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),  
#    url(r'^ratings/', include('ratings.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/reviews/course_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load ratings %}
{% load avg_ratings %}
{% load user_ratings %}

{% block title %}
<h2>{{course.course_id}}: {{ course.course_name }}</h2>
{% avg_ratings course %}
<h5>{{ course.review_set.count }} reviews</h5>


{% endblock %}

{% block content %}
<h3>Course Credits:</h3>
<p>{{course.course_credit}}</p>
<h3>Course Pre-requisites:</h3>
<p>{{course.course_preReq}}</p>
<h3>Course Details:</h3>
<p> {% autoescape on %}
    {{ course.course_details | linebreaksbr }}
{% endautoescape %}</p>
<h3>Recent reviews</h3>

{% if course.review_set.all %}
<div class="row">
    {% for review in course.review_set.all %}
    <div class="col-xs-6 col-lg-4">
       <p><em>{{ review.summary }}</em></p>
        {% user_ratings review.course review.rating %}
        <h6>by <a href="{% url 'user_detail' review.user_name %}" >{{ review.user_name }}</a></h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this course yet</p>
{% endif %}



<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' course.id %}" method="post" class="form">

    {% csrf_token %}
        {% for field in form %}
            {% bootstrap_field field%}
        {% endfor%}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}

templates/reviews/course_list.html
{% extends 'base.html' %}

{% block title %}
<h3><center>Course List</center></h3>
{% endblock %}

{% block content %}
{% if course_list %}<center>
<form id="search"> <center>
<select id="org" name="course_list" onChange="window.document.location.href=this.options[this.selectedIndex].value;">
 <option  value="" selected="selected">---SELECT COURSE---</option>
{% for course in course_list %}
   <option value="{% url 'reviews:course_detail' course.id %}"
       {% if course == current_course %}selected="selected"{% endif %}>
       <h4><a href="{% url 'reviews:course_detail' course.id %}">
        {{ course.course_id }}: {{course.course_name}}
        </a></h4>
   </option>
{% endfor %}
</select></center>
</form></center>
<div>
<ul class="kdlist">
    {% for course in course_list %}
    <li class="kdlist">
    <div class="col-xs-6 col-lg-4">
         
        <h4><a href="{% url 'reviews:course_detail' course.id %}">
        {{ course.course_id }}: {{course.course_name}}
        
        <h5>{{ course.review_set.count }} reviews</h5> </a></h4>
    </div>
    </li>
    {% endfor %}
</ul>
</div>
{% else %}
    <p>No courses are available.</p>
{% endif %}
{% endblock %}

templates/reviews/faculty_list.html
{% extends 'base.html' %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
                       integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
                       crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"
                       crossorigin="anonymous">

{% block title %}
<center>
  <h1><u>Faculty list</u></h1>
{% endblock %}
</center>
{% block content %}
{% if faculty_list %}
<form id="search" align="right">
  <select id="org" name="faculty_list" onChange="window.document.location.href=this.options[this.selectedIndex].value;">
    <option  value="" selected="selected">---Search for Professors---</option>
    {% for faculty in faculty_list %}
    <option value= {{faculty.fac_webpage}}
                      {% if faculty == current_faculty %}selected="selected"{% endif %}>
    <h4><a href={{faculty.fac_webpage}}>
        {{ faculty.fac_name }}
      </a></h4>
    </option>
    {% endfor %}
  </select>
</form>
<center>
<div class="row">
  {% for faculty in faculty_list %}
  <section class="col-md-10 col-md-offset-1">
    <header>
      <h3><a href= {{faculty.fac_webpage}} > {{ faculty.fac_name }} </a></h3>
    </header>


    <p>{{ faculty.fac_id }}:</p><p> {{faculty.fac_data }}</p>

  </section>
  {% endfor %}
</div></center>
{% else %}
<p>No faculties are available.</p>
{% endif %}
{% endblock %}

templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load user_ratings %}

{% block title %}
<!--<<<<<<< HEAD-->
<h2><a href="{% url 'reviews:course_detail' review.course.id %}">{{ course.course_id }} : {{ course.course_name }}</a></h2>
{% endblock %}

{% block content %}

{% user_ratings course review.rating %}
<h4>by <a href="{% url 'user_detail' review.user_name %}" >{{ review.user_name }}</a></h4>
<!--=======
<h2><a href="{#% url 'reviews:course_detail' review.course.id %}">{{review.course.courseid}}{{ review.course.course_name }#}</a></h2>
{#% endblock %#}

{#% block content %#}
<h4>Rated {#{ review.rating }} of 5 by <a href="{% url 'user_detail' review.user_name %}" >{{ review.user_name }#}</a></h4>
>>>>>>> 781701fd9c94fe128ccac2de6ad28d2a8116f036 -->
<p>{{ review.pub_date }}</p>
<p>Summary : {{review.summary}}</p>
<p>{{ review.comment }}</p>
{% endblock %}

templates/reviews/review_list.html
{% extends 'base.html' %}
{% load user_ratings %}
{% block title %}
<h3>Reviews</h3>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.course.course_id }}
        </a></h4>
<!--<<<<<<< HEAD-->
        {% user_ratings review.course review.rating %}
        <h6> by {{ review.user_name }}</h6>
<!--=======
        <h6>Rated {#{ review.rating }#} of 5 by <a href="{#% url 'user_detail' review.user_name %#}">
            {#{ review.user_name }#}</a></h6>
>>>>>>> 781701fd9c94fe128ccac2de6ad28d2a8116f036 -->
        <p>{{ review.summary }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}