log/urls.py
#!python
# log/urls.py
from django.conf.urls import url
from . import views
from log import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^home$', views.home, name='home'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^$',views.homepage, name='homepage'),
    url(r'^review$', views.review_list, name='review_list'),
    url(r'^apphome$', views.apphome, name='apphome'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^user/(?P<user_name>[a-z]+)/$', views.user_detail, name='user_detail'),
    url(r'^course$', views.course_list, name='course_list'),
    url(r'^faculty$', views.faculty_list, name='faculty_list'),
    url(r'^course/(?P<course_id>[0-9]+)/$', views.course_detail, name='course_detail'),
    url(r'^course/(?P<course_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^user_login$', views.user_login, name='auth'),
]

project/urls.py
#!python
# project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# Add this import
from django.conf.urls.static import static
from django.contrib.auth import views
from log.forms import LoginForm
from log.views import user_login

urlpatterns = [
    url(r'^reviews/', include('log.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^login_failed/$', views.login, {'template_name': 'login_failed.html', 'authentication_form': LoginForm}, name='login_failed'),
    url(r'^login1/$', user_login, name='auth'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),  
#    url(r'^ratings/', include('ratings.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/apphome.html
{% extends 'base.html' %}
{% load user_ratings %}

{% block title %}
<h3>Welcome to the Student Course Review</h3>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<h4>Latest Reviews</h4>
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.course.course_id }}
        </a></h4>
        {% user_ratings review.course review.rating %}
        <h6>by <a href="{% url 'user_detail' review.user_name %}">
            {{ review.user_name }}</a></h6>
        <p>{{ review.summary }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

templates/base.html
	{% load staticfiles %}
    {% load static %}

	<!DOCTYPE html>
	<html>

	<head>

	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	    <title>Course Reviews</title>

	    <!-- Core CSS - Include with every page -->
	    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"><style>
body{ background: url(static/bac.jpg) no-repeat center fixed;
  background-size: cover;
}
ul.kdlist {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 150%;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
}

li.kdlist a {
    display: block;
    color: #000;
    padding: 40px 80px;
    text-decoration: none;
}

li.kdlist a.active {
    background-color: #4CAF50;
    color: white;
}

li.kdlist a:hover:not(.active) {
    background-color: #37474f;
    color: white;
} 
#org {
    background-color: #546e7a;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

#org:hover, #org:focus {
    background-color: #455a64;
}

#org {
    position: relative;
    display: inline-block;
}

</style>
	</head>

	<body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'apphome' %}">CS252 Project: Course Review</a>
<!--	    </div>

        <div id="navbar" class="navbar-collapse collapse">-->
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:course_list' %}">Course List</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Review List</a></li>   <li><a href="{% url 'reviews:faculty_list' %}">Faculty List</a></li>
            </ul>
        </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="/home">Home</a></li>
	            <li><a target="_blank" href="https://www.cse.iitk.ac.in/pages/AntiCheatingPolicy.html">Academic Policy</a></li>
	            <li class="divider"></li>
	            <li><a href="{% url 'contact' %}">About Us</a></li>
	            <li class="divider"></li>
	            <li><a href="{% url 'homepage' %}">Logout</a></li>
	          </ul>
	        </li>

	      </ul>
	    </div>
	  </div>
	</nav>
                {% block title %}
                {% endblock %}
	            {% block content %}
	            {% endblock %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

	    <!-- Core Scripts - Include with every page -->
	    <script src = "{% static 'js/jquery.min.js' %}"></script>

	    <script src = "{% static 'js/bootstrap.min.js' %}"></script>

	    {% block javascript %}
	    {% endblock %}

	</body>

	</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}
 This project has been created as a part of course CS-252 : Computing Laboratory - II. 
{% endblock %}

{% block content %}
<h3> For further details contact the following :</h3>

               <div class="contacti">
               <a target="_blank" href="">
             <img src="static/user1.png" alt="Ankur" width="700" height="300">
  </a>
  <div class="contactd">Ankur Kumar
<br>14109<br>Department : CSE<br>
ankurk@iitk.ac.in</div>
</div>

  <div class="contacti">
               <a target="_blank" href="http://home.iitk.ac.in/~ishika/">
             <img src="static/user2.png" alt="Ishika " width="700" height="300">
  </a>
  <div class="contactd">Ishika Soni
<br>14275<br>Department : CSE<br>
ishika@iitk.ac.in</div>
</div>
  <div class="contacti">
               <a target="_blank" href="https://www.linkedin.com/in/kritagya-dabi-2a1057104?trk=nav_responsive_tab_profile">
             <img src="static/user1.png" alt="Kritagya Dabi" width="700" height="300">
  </a>
  <div class="contactd">Kritagya Dabi
<br>14326<br>Department : CSE<br>
kdabi@iitk.ac.in</div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load user_ratings %}

{% block content %}

<div class="container">
<div class="row">

<div class="jumbotron">
  <h1>Hello {{request.user.username}}</h1>
  <p>Welcome to your Dashboard</p>
<h3> Reviews submitted by you :</h3>
{% if latest_review_list %}
<div class="row" style="background-color:white">
    {% for review in latest_review_list %}
    {% ifequal review.user_name request.user.username %}
    <center>
    <div class="col-xs-6 col-lg-4">
        <h2><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.course.course_id }}
        </a></h2>
        {% user_ratings review.course review.rating %} 
        <h6> by <a href="{% url 'user_detail' review.user_name %}">
            {{ review.user_name }}</a></h6>
        <p>{{ review.summary }}</p>
    </div>
    </center>
    {% endifequal %}
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}

</div>
</div>
</div>
{% endblock %}

templates/homepage.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Student Course Review</title>
    
    <meta name="viewport" content="width=device-width" />
    
    <style>
        /* Body */
        body {background: url('static/book.jpg') center center fixed; background-size:cover;
            font-family: 'open sans', Arial, sans-serif; display: flex; min-height: 100vh;flex-direction: column;}

        .dimmer {position: fixed; top:0; bottom:0; left:0; right:0; width: 100%; height: 100%; z-index: -1; background: url('/images/layer.png') top left repeat; }



        /* Header & Logo */
        
        .logo { text-transform: uppercase; margin: 36px 0px 30px 0px; font-weight: 600; text-align: center;}
        .logo .text { display: inline-block; color:white; }
        .logo .top { display: block; /*color: #E22E1F;*/ letter-spacing: .4em; color:white; text-shadow: 4px 4px 0px rgba(0,0,0,0.4);}
        .logo .bottom { display: block; /*color: #27BFC4;*/ font-size: .5em; letter-spacing: .5em; color:white; text-shadow: 2px 2px 0px rgba(0,0,0,0.4); }
        .logo img {
            -webkit-transition: all 1s ease-in-out;
            -moz-transition: all 1s ease-in-out;
            -o-transition: all 1s ease-in-out;
            -ms-transition: all 1s ease-in-out;
        }
        .logo img:hover {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            -ms-transform: rotate(360deg)
        }


        /* Content */
        .content { text-align: center; font-size:3em; flex:1 0 0; }
        h2 { font-size:1em; text-shadow: 4px 4px 0px rgba(0,0,0,0.4); margin: 0 0 34px 0; color: white; font-weight: bold; }
        .centered { padding-top: 4%; }


        
        /* Footer */
        footer { padding-top: 20px; /*background-color: #fff; webkit-box-shadow: 0px -5px 11px 0px rgba(50, 50, 50, 0.25); box-shadow: 0px -5px 11px 0px rgba(50, 50, 50, 0.25); */}
        .footer-right {text-align: right; float: right; width: 50%; display:inline-block; padding-right:15px;
             font-size:1.5em; color: white; font-weight: bold;padding-top:10px;
        }

        .footer-right a {color:white; padding: 4px 10px 4px 10px; text-shadow: 2px 2px 0px rgba(0,0,0,0.4); text-decoration:none}
        .footer-right a:hover {color:#E0E0E0; text-decoration:none}
        .header-right {text-align: right; float: right; width: 50%; display:inline-block; padding-right:15px;
             font-size:1.5em; color: white; font-weight: bold;padding-top:10px;
        }

        .header-right a {color:white; padding: 4px 10px 4px 10px; text-shadow: 2px 2px 0px rgba(0,0,0,0.4); text-decoration:none}
        .header-right a:hover {color:#E0E0E0; text-decoration:none}


        .social { display: inline-block; color: #ffffff; padding: 0 4px 10px 4px; text-shadow: 4px 4px 0px rgba(0,0,0,0.3);
        }

    </style>
</head>
<body>
<div class="dimmer"></div>
<header>
   <div class="header-right">
   <a href="{% url 'login' %}">Login</a>
   </div>
</header>
    <div class="container-fluid">
        <h1 class="logo"><img src="static/logo.jpg" height="102" width="102">
            <!--<div class="text">-->
            <span class="top">Student</span><span class="bottom">Course Review</span>
            <!--</div>-->
        </h1>
    </div>

<div class="content">
    <div class="centered">
        <div class="container-fluid">
            <h2>The place to review your College courses</h2>
        </div>
        
        <div class="container-fluid">
            <p >
                Join other Students Reviewing their Courses
            </p>
        </div>
    </div>
</div>
<footer>
    <div class="footer-right">
        <a href="http://www.iitk.ac.in">IIT Kanpur, India </a>
    </div>
</footer>
</body>
</html>

templates/login.html
{% extends 'base.html' %}


{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Please Sign In</h3>
        </div>
        <div class="panel-body">
          <form method="post" action="{% url 'auth' %}">
            {% csrf_token %}
            <p class="bs-component">
            <table>
              <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
              </tr>
              <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
              </tr>
            </table>
            </p>
            <p class="bs-component">  
            <center><input class="btn btn-success btn-sm" type="submit" value="login" /></center>
            </p>
            <input type="hidden" name="next" value="{{ next }}" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block javascript %}

<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}

templates/login_failed.html
{% extends 'base.html' %}


{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}
<p>Authentication Failed. Your username and password didn't match. Please try again.</p>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Please Sign In</h3>
        </div>
        <div class="panel-body">
          <form method="post" action="{% url 'auth' %}">
            {% csrf_token %}
            <p class="bs-component">
            <table>
              <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
              </tr>
              <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
              </tr>
            </table>
            </p>
            <p class="bs-component">  
            <center><input class="btn btn-success btn-sm" type="submit" value="login" /></center>
            </p>
            <input type="hidden" name="next" value="{{ next }}" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block javascript %}

<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}User Registration{% endblock %}
{% block head %}User Registration{% endblock %}
{% block content %}
<form method="post" action=".">
{{ form.as_p }}
<input type="submit" value="register" />
{% csrf_token %}
</form>
{% endblock %}

templates/user_detail.html
{% load static %}
<center>
<img src= "{% static "user.jpg" %}" height="500" width="500">
<h2> Username: <a href="http://home.iitk.ac.in/~{{user.username}}">{{user.username}} </a></h2>
</center>

templates/working_login.html
<HTML>
<HEADER>
    <TITLE>Rango</TITLE>
</HEADER>
<BODY>
        <FORM id="login_form" method="post" action="/user_login">
        {% csrf_token %}
                Username:
                <input type="text" name="username" value="" id="username" size="50" />
            <br />
                Password:
                <input type="password" name="password" value="" id="password" size="50" />
                <br />
        <INPUT type="submit" name="submit" value="submit" />
        </FORM>
</BODY>
</HTML>